export { RequiredFieldsSettings } from './RequiredFieldsSettings';
export { CoreSettings } from './CoreSettings';
export { WatermarkSettings } from './WatermarkSettings';
export { DashboardSettings } from './DashboardSettings';
export { DashboardConfigSettings } from './DashboardConfigSettings';
export { ModulesSettings } from './ModulesSettings';
export { PrestadorSettingsGeneral } from './PrestadorSettingsGeneral';
export { PrestadorSettingsDados } from './PrestadorSettingsDados';
export { PrestadorSettingsBancarios } from './PrestadorSettingsBancarios';
